---
- name: Install nginx
  hosts: localhost
  become: true
  
  tasks:
    - name: update cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: latest

    - name: Start Apache2
      service:
        name: apache2
        state: started
        enabled: yes
