---
- name: Stop EC2 instances
  hosts: localhost
  gather_facts: True

  tasks:
    - name: Stop EC2 instances using aws module
      community.aws.ec2_instance_info:
        region: us-east-1
      register: ec2_info

    - name: Display outputs
      debug: msg="{{item.instance_id}}"
      with_items: "{{ec2_info.instances}}"

    - name: Stop instances
      amazon.aws.ec2_instance:
        instance_ids: "{{item.instance_id}}"
        region: us-east-1
        state: stopped
        wait: yes
      with_items: "{{ec2_info.instances}}"
